
services:
  # app:
  #   build: .
  #   container_name: nestjs_app
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #     - redis
  #   networks:
  #     - nest_network

  postgres:
    image: postgres:latest
    container_name: nestjs_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest_network

  redis:
    image: redis:latest
    container_name: nestjs_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - nest_network

volumes:
  postgres_data:

networks:
  nest_network: